#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s    # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_interval: 15s    # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 10s

  external_labels:
    environment: ip-10-0-192-98.ec2.internal

### alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 34.237.151.53:9093
      # - ip-10-0-192-98.ec2.internal:9093
      # - 54.227.162.130:9093


# alerting:
#   alertmanagers:
#   - scheme: http
#     # path_prefix: /alertmanager
#     path_prefix: /#
#     tls_config:
#       insecure_skip_verify: true
#     static_configs:
#     - targets:
#       - 54.227.162.130:9093


rule_files:
  - /etc/prometheus/rules/*.rules
  - /etc/prometheus/rules/rules-alert.yml
  - /etc/prometheus/rules/awesome-alerts.yml


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - ip-10-0-192-98.ec2.internal:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
  - job_name: 'alertmanager'
    # metrics_path: /alerts
    static_configs:
      - targets: 
        # - ip-10-0-192-98.ec2.internal:9093
        - 34.237.151.53:9093
  - job_name: 'grafana'
    static_configs:
      - targets: 
        - ip-10-0-192-98.ec2.internal:3000
  - job_name: 'node_exporter'
    static_configs:
    # - targets: ['10.0.192.40:9100']
      - targets: ['54.227.162.130:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['54.227.162.130:8000']
  # - job_name: 'docker'
  #        # metrics_path defaults to '/metrics'
  #        # scheme defaults to 'http'.
  #   static_configs:
  #     # - targets: ['10.0.192.40:9323']
  #     - targets: ['54.227.162.130:9323']
  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323
  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     # - targets: ['pushgateway:9091']
  #     # - targets: ['10.0.192.40:9091']
  #     - targets: ['54.227.162.130:9091']

  # - job_name: 'validator'
  #    static_configs:
  #    - targets: ['localhost:80']

  # sg-0b516a4a2ff12207a
